CREATE TABLE Localizacao
(
	CEP VARCHAR(8)NOT NULL,
	RUA VARCHAR(255)NOT NULL,
	BAIRRO VARCHAR(255)NOT NULL,
	CIDADE VARCHAR(255)NOT NULL,
	PRIMARY KEY (CEP)
);

CREATE TABLE Estacao
(
	ID_ESTACAO VARCHAR(255) NOT NULL,
	QTD_ARMAZENAMENTO VARCHAR(255) NOT NULL,
	QTD_OCUPADA VARCHAR(255) NOT NULL,
	CEP VARCHAR(255) NOT NULL,
	NUM VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_ESTACAO),
	FOREIGN KEY (CEP) REFERENCES Localizacao(CEP)
);

CREATE TABLE Cartao
(
	NUMERO_CARTAO VARCHAR(255) NOT NULL,
	SALDO_CARTAO VARCHAR(255) NOT NULL,
	ESTADO_CARTAO VARCHAR(255) NOT NULL,
	TIPO_CARTAO VARCHAR(255) NOT NULL,
	VALIDADE_CARTAO TIMESTAMP NOT NULL,
	PRIMARY KEY (NUMERO_CARTAO)
);

CREATE TABLE Usuario
(
	CPF VARCHAR(255)NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	DATA_NASCIMENTO TIMESTAMP NOT NULL,
	NUMERO_CARTAO VARCHAR(255) NOT NULL,
	PRIMARY KEY (CPF),
	FOREIGN KEY (NUMERO_CARTAO) REFERENCES Cartao(NUMERO_CARTAO)
);

CREATE TABLE Fornecedor
(
	CNPJ VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (CNPJ)
);

CREATE TABLE Bicicleta
(
	ID_BICICLETA VARCHAR(255) NOT NULL,
	TAMANHO VARCHAR(255) NOT NULL,
	MODELO VARCHAR(255) NOT NULL,
	ESTADO_CONSERVACAO VARCHAR(255) NOT NULL,
	ATIVA BOOLEAN NOT NULL,
	CNPJ_FORNECEDOR VARCHAR(255) NOT NULL,
	ID_ESTACAO VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_BICICLETA),
	FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES Fornecedor(CNPJ),
	FOREIGN KEY (ID_ESTACAO) REFERENCES Estacao(ID_ESTACAO)
);

CREATE TABLE Aluguel
(
	ID_ALUGUEL VARCHAR(255) NOT NULL,
	ID_BICICLETA VARCHAR(255) NOT NULL,
	CPF_USUARIO VARCHAR(255) NOT NULL,
	DATA_INICIO TIMESTAMP NOT NULL,
	DATA_FIM TIMESTAMP,
	ID_ESTACAO_INICIO VARCHAR(255) NOT NULL,
	ID_ESTACAO_FIM VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_ALUGUEL),
	FOREIGN KEY (ID_BICICLETA) REFERENCES Bicicleta(ID_BICICLETA),
	FOREIGN KEY (CPF_USUARIO) REFERENCES Usuario(CPF),
	FOREIGN KEY (ID_ESTACAO_INICIO) REFERENCES Estacao(ID_ESTACAO),
	FOREIGN KEY (ID_ESTACAO_FIM) REFERENCES Estacao(ID_ESTACAO)
);

CREATE TABLE Conserta
(
	ID_BICICLETA VARCHAR(255) NOT NULL,
	CNPJ_FORNECEDOR VARCHAR(255) NOT NULL,
	DATA_INICIO TIMESTAMP NOT NULL,
	DATA_FIM TIMESTAMP,
	PRAZO TIMESTAMP NOT NULL,
	PRIMARY KEY (ID_BICICLETA, CNPJ_FORNECEDOR, DATA_INICIO),
	FOREIGN KEY (ID_BICICLETA) REFERENCES Bicicleta(ID_BICICLETA),
	FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES Fornecedor(CNPJ)
);

CREATE TABLE Armazena
(
	ID_ESTACAO VARCHAR(255) NOT NULL,
	ID_BICICLETA VARCHAR(255) NOT NULL,
	DATA_INICIO VARCHAR(255) NOT NULL,
	DATA_FIM VARCHAR(255),
	PRIMARY KEY (ID_BICICLETA, ID_ESTACAO, DATA_INICIO),
	FOREIGN KEY (ID_BICICLETA) REFERENCES Bicicleta(ID_BICICLETA),
	FOREIGN KEY (ID_ESTACAO) REFERENCES Estacao(ID_ESTACAO)
);