INSERT INTO Localizacao VALUES ("13000001", "Estrada da Rhodia", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083400", "Rua Joao Guimaraes Rosa", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083490", "Praca Doutor Heraldo da Rocha Novaes", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083590", "Rua Roxo Moreira", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083740", "Rua Doutor Luciano Venere Decourt", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083755", "Rua Doutor Antonio Augusto de Almeida", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083765", "Rua Doutor Shigeo Mori", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083830", "Avenida Professor Atilio Martini", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083851", "Avenida Erico Verissimo", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083852", "Avenida Albert Einstein", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083859", "Rua Sergio Buarque de Holanda", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083874", "Avenida Martin Luther King", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083879", "Praca Carlos Drummond de Andrade", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13083895", "Praca Henfil", "Cidade Universitaria", "Campinas");
INSERT INTO Localizacao VALUES ("13084008", "Avenida Albino Jose Barbosa de Oliveira", "Barao Geraldo", "Campinas");
INSERT INTO Localizacao VALUES ("13084012", "Avenida Santa Isabel", "Barao Geraldo", "Campinas");
INSERT INTO Localizacao VALUES ("13084085", "Praca Augusta Pires de Moraes", "Barao Geraldo", "Campinas");
INSERT INTO Localizacao VALUES ("13084095", "Rua Agostinho Pattaro", "Barao Geraldo", "Campinas");
INSERT INTO Localizacao VALUES ("13084133", "Praca Flavio Ribeiro da Silva", "Barao Geraldo", "Campinas");
INSERT INTO Localizacao VALUES ("13106025", "Rua Bertrand Russel", "Cidade Universitaria", "Campinas");